# Generated by Django 4.2.5 on 2023-09-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name='User ID')),
                ('name', models.CharField(max_length=50, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('website', models.CharField(max_length=20, verbose_name='User Website')),
            ],
        ),
    ]
