# Generated by Django 4.2.3 on 2023-09-27 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='User ID')),
                ('name', models.CharField(max_length=50, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('website', models.CharField(max_length=50, verbose_name='User Website')),
            ],
        ),
    ]
