# Generated by Django 4.2.5 on 2023-09-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_userid_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(max_length=50, verbose_name='User Website'),
        ),
    ]
