version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - backend

  flask-app:
    image: flask-app:1.0
    container_name: flask-app
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
    external: true
volumes:
  data:
